# Generated by Django 4.1.6 on 2023-02-08 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0002_alter_menuitem_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
    ]
