# Generated by Django 4.1.6 on 2023-02-10 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0004_alter_order_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
