# Generated by Django 4.1.6 on 2023-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0005_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(db_index=True, max_length=225, unique=True),
        ),
    ]
